spring:
  banner:
    location: classpath:banner/banner-local.txt

  messages:
    basename: i18n/messages
    encoding: UTF-8

  datasource:
    url: jdbc:p6spy:postgresql://localhost:5432/wsc_ktds?currentSchema=esign
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: wscadmin
    password: Wscadmin1234!

    hikari:
      connection-timeout: 30000
      minimum-idle: 3
      maximum-pool-size: 5

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        default_batch_fetch_size: 500
        query:
          in_clause_parameter_padding: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

app:
  file:
    location: /upload/files/
